[env:wt32-sc01-plus]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

;On the air (OTA) upload hange from port COM4 to device IP
;Run terminal command = pio run -t upload
; upload_port = 192.168.1.190
; upload_protocol = espota

;USB OTG/ serial upload
upload_port = COM3
upload_speed = 921600
monitor_speed = 115200

board_upload.flash_size = 8MB
board_build.psram = enabled
board_build.partitions = partitions_custom.csv
board_build.filesystem = littlefs

build_flags =
    -DLGFX_USE_V1
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_COLOR_DEPTH=16
    -DLV_COLOR_16_SWAP=0
    -DLV_USE_USER_DATA=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_48=1
    -D CONFIG_ASYNC_TCP_USE_WDT=0
    -D ARDUINO_LOOP_STACK_SIZE=16384
    -D CONFIG_ESP_TASK_WDT_PANIC=0
    -D CONFIG_ESP_TASK_WDT=0

lib_deps =
    lovyan03/LovyanGFX@^1.1.12
    lvgl/lvgl@^8.3.11
    256dpi/MQTT@^2.5.2
    bblanchon/ArduinoJson@^7.0.4
    mathieucarbou/ESPAsyncWebServer@^3.1.5
    Bodmer/TJpg_Decoder@^1.0.8

extra_scripts =
    post:fix_esptool.py
    post:fix_otadata_offset.py